#!/bin/sh
dnf install -y openssh-server python2-dnf
ssh-keygen -q -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
echo 'root:foobar' | chpasswd
# start sshd in background
/usr/sbin/sshd
echo SSHD READY
# wait forever
tail -f /dev/null
